"use client";

import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import "./globals.css";
import Head from "next/head";
//import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const client = new ApolloClient({
    uri: "http://localhost:3000/api/products",
    cache: new InMemoryCache(),
  });
  return (
    <html lang="en">
      <Head>
        <title>크리스몰</title>
      </Head>
      <body className="whitespace-nowrap">
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
